#include "../../MockDevices/SparkFunSX1509.h"
#include "../../MockDevices/Adafruit_PWMServoDriver.h"
#include "../../MockDevices/Adafruit_ADS1015.h"
#include "../../arduino-mock/Wire.h"
#include "Wall.h"
#include "WallCore.cpp"